In [1]:
import requests
import bs4
import warnings 
warnings.filterwarnings('ignore')
from bs4 import BeautifulSoup
import pandas as pd
import re

Question no.1

In [51]:
page=requests.get(' https://www.cnbc.com/world/?region=world ')
page

In [52]:
soup=BeautifulSoup(page.content,'html')

In [55]:
Headings=[]

for heading in soup.find_all('div',class_='LatestNews-headlineWrapper'):
    i=heading.find('a')
    Headings.append(i.text.strip())

In [57]:
Date=[]

for date in soup.find_all('time',class_='LatestNews-timestamp'):
    Date.append(date.text.strip())

In [80]:
News_link=[]

for link in soup.find_all('a',class_='LatestNews-headline'):
    i=link.get('href')
    News_link.append(i)

In [82]:
len(Headings),len(Date),len(News_link)

(30, 30, 30)

In [83]:
News=pd.DataFrame({'Heading':Headings,'Date':Date,'News_link':News_link})

In [84]:
News

,Heading,Date,News_link
0,Daimler Truck surges 13% to new record on bump...,17 Min Ago,https://www.cnbc.com/2024/03/01/daimler-truck-...
1,10-year Treasury yield rises as investors weig...,55 Min Ago,https://www.cnbc.com/2024/03/01/us-treasury-yi...
2,"In a bizarre British by-election, a pro-Palest...",59 Min Ago,https://www.cnbc.com/2024/03/01/this-is-for-ga...
3,"'Stupidity' poses a bigger threat than AI, CEO...",1 Hour Ago,https://www.cnbc.com/2024/03/01/defense-leonar...
4,Mourners arrive for Navalny funeral in Moscow;...,2 Hours Ago,https://www.cnbc.com/2024/03/01/russia-ukraine...
5,European markets climb ahead of euro zone infl...,2 Hours Ago,https://www.cnbc.com/2024/03/01/europe-markets...
6,CNBC Daily Open: Wall Street unfazed by hot in...,3 Hours Ago,https://www.cnbc.com/2024/03/01/cnbc-daily-ope...
7,"India 'easily' the fastest growing economy, IM...",4 Hours Ago,https://www.cnbc.com/2024/03/01/india-easily-f...
8,Ukraine's losses on the battlefield could make...,4 Hours Ago,https://www.cnbc.com/2024/03/01/ukraines-losse...
9,Europe is having its worst earnings season in ...,4 Hours Ago,https://www.cnbc.com/2024/03/01/europe-is-havi...
10,UK to lead European real estate boom as buyers...,4 Hours Ago,https://www.cnbc.com/2024/03/01/uk-europe-real...
11,India approves three chip plants with over $15...,6 Hours Ago,https://www.cnbc.com/2024/03/01/india-boosts-c...
12,China calls on foreign businesses to share the...,6 Hours Ago,https://www.cnbc.com/2024/03/01/china-calls-on...
13,What tech giants are betting on — from robot d...,6 Hours Ago,https://www.cnbc.com/2024/03/01/latest-tech-ga...
14,Facebook is getting rid of the News tab in the...,7 Hours Ago,https://www.cnbc.com/2024/03/01/facebook-is-ge...
15,Japan's factory activity contracts most in ove...,7 Hours Ago,https://www.cnbc.com/2024/03/01/japans-factory...
16,CNBC Daily Open: Hot inflation data but could ...,9 Hours Ago,https://www.cnbc.com/2024/03/01/cnbc-daily-ope...
17,Jim Cramer explains why the market rallied on ...,10 Hours Ago,https://www.cnbc.com/2024/02/29/jim-cramer-exp...
18,Tesla stands to earn billions by opening U.S. ...,10 Hours Ago,https://www.cnbc.com/2024/02/29/tesla-to-earn-...
19,Psychologist: The No. 1 'gentle parenting' mis...,10 Hours Ago,https://www.cnbc.com/2024/02/29/psychologist-t...
20,10 best places to buy a winter vacation home b...,10 Hours Ago,https://www.cnbc.com/2024/02/29/vacasa-top-us-...
21,CEO says Hormel Foods is well-positioned as we...,10 Hours Ago,https://www.cnbc.com/2024/02/29/ceo-says-horme...
22,Cramer's Lightning Round: Signet Jewelers is a...,10 Hours Ago,https://www.cnbc.com/2024/02/29/cramers-lightn...
23,"Japan's Nikkei 225 closes shy of 40,000 record...",10 Hours Ago,https://www.cnbc.com/2024/03/01/asia-markets-....
24,India’s Byju’s lost more than $20 billion in v...,11 Hours Ago,https://www.cnbc.com/2024/03/01/the-rise-and-f...
25,Veteran advisor sees signs of an AI-fueled mar...,11 Hours Ago,https://www.cnbc.com/2024/03/01/veteran-adviso...
26,,11 Hours Ago,https://www.cnbc.com/2024/03/01/investors-shou...
27,,11 Hours Ago,https://www.cnbc.com/2024/03/01/magnificent-7-...
28,Death of Foremost CEO Angela Chao under 'crimi...,11 Hours Ago,https://www.cnbc.com/2024/02/29/angela-chao-de...
29,Stock futures edge higher after the market wra...,11 Hours Ago,https://www.cnbc.com/2024/02/29/stock-market-t...

Question no.2

In [4]:
page=requests.get('https://www.keaipublishing.com/en/journals/artificial-intelligence-in-agriculture/most-downloaded-articles/')
page

In [5]:
soup=BeautifulSoup(page.content,'html')

In [41]:
Title=[]

for title in soup.find_all('h2',class_='h5 article-title'):
    Title.append(title.text.strip())

In [43]:
Date=[]

for date in soup.find_all('p',class_='article-date'):
    Date.append(date.text.strip())

In [47]:
Author=[]

for author in soup.find_all('p',class_='article-authors'):
    Author.append(author.text.strip())

In [49]:
len(Title),len(Date),len(Author)

(25, 25, 25)

In [50]:
Paper=pd.DataFrame({'Paper_title':Title,'Date':Date,'Author':Author})
Paper

,Paper_title,Date,Author
0,Implementation of artificial intelligence in a...,2020,Tanha Talaviya | Dhara Shah | Nivedita Patel...
1,Review of agricultural IoT technology,2022,Jinyuan Xu | Baoxing Gu | Guangzhao Tian
2,A comprehensive review on automation in agricu...,June 2019,Kirtan Jha | Aalap Doshi | Poojan Patel | M...
3,Automation and digitization of agriculture usi...,2021,A. Subeesh | C.R. Mehta
4,Applications of electronic nose (e-nose) and e...,2020,Juzhong Tan | Jie Xu
5,Fruit ripeness classification: A survey,March 2023,Matteo Rizzo | Matteo Marcuzzo | Alessandro ...
6,A review of imaging techniques for plant disea...,2020,Vijai Singh | Namita Sharma | Shikha Singh
7,Deep learning based computer vision approaches...,2022,V.G. Dhanya | A. Subeesh | N.L. Kushwaha | ...
8,Comparison of CNN-based deep learning architec...,September 2023,Md Taimur Ahad | Yan Li | Bo Song | Touhid ...
9,Transfer Learning for Multi-Crop Leaf Disease ...,2022,Ananda S. Paymode | Vandana B. Malode
10,Plant disease detection using hybrid model bas...,2021,Punam Bedi | Pushkar Gole
11,Machine learning in nutrient management: A review,September 2023,Oumnia Ennaji | Leonardus Vergütz | Achraf E...
12,DeepRice: A deep learning and deep feature bas...,March 2024,P. Isaac Ritharson | Kumudha Raimond | X. An...
13,How artificial intelligence uses to achieve th...,June 2023,Vilani Sachithra | L.D.C.S. Subhashini
14,Machine learning for weed–plant discrimination...,December 2023,Filbert H. Juwono | W.K. Wong | Seema Verma ...
15,Examining the interplay between artificial int...,2022,Abderahman Rejeb | Karim Rejeb | Suhaiza Zai...
16,Deep convolutional neural network models for w...,2022,A. Subeesh | S. Bhole | K. Singh | N.S. Cha...
17,A systematic review of machine learning techni...,2022,Md Ekramul Hossain | Muhammad Ashad Kabir | ...
18,A review on computer vision systems in monitor...,2020,Cedric Okinda | Innocent Nyalala | Tchalla K...
19,Crop diagnostic system: A robust disease detec...,December 2023,R. Abbasi | P. Martinez | R. Ahmad
20,Artificial cognition for applications in smart...,2020,Misbah Pathan | Nivedita Patel | Hiteshri Ya...
21,Explainable artificial intelligence and interp...,2022,Masahiro Ryo
22,Blockchain: A new safeguard for agri-foods,2020,Jie Xu | Shuang Guo | David Xie | Yaxuan Yan
23,Study on body temperature detection of pig bas...,March 2019,Zaiqin Zhang | Hang Zhang | Tonghai Liu
24,Vision Intelligence for Smart Sheep Farming: A...,March 2024,Galib Muhammad Shahriar Himel | Md. Masudul I...

1) Write a python program to display IMDB’s Top rated 100 Indian movies data

'https://www.imdb.com/list/ls056092300/' (i.e. name, rating, year ofrelease) and make data frame.

In [142]:
page=requests.get('https://www.imdb.com/list/ls056092300/')
page

In [147]:
soup=BeautifulSoup(page.content)

In [148]:
Name=[]
 
for i in soup.find_all('h3',class_='lister-item-header'):
    name=i.find('a')
    Name.append(name.text)

In [149]:
Rating=[]
for i in soup.find_all('div',class_='ipl-rating-star small'):
    rating=i.text.replace('\n','')
    Rating.append(rating)

In [150]:
Year_of_release=[]

for i in soup.find_all('span',class_='lister-item-year text-muted unbold'):
    Year_of_release.append(i.text.strip())

In [151]:
len(Name),len(Rating),len(Year_of_release)

(100, 100, 100)

In [152]:
Film=pd.DataFrame({'Name':Name,'Rating':Rating,'Year_of_release':Year_of_release})
Film

                                 Name Rating Year_of_release
0                     Ship of Theseus      8          (2012)
1                              Iruvar    8.4          (1997)
2                     Kaagaz Ke Phool    7.8          (1959)
3   Lagaan: Once Upon a Time in India    8.1          (2001)
4                     Pather Panchali    8.2          (1955)
..                                ...    ...             ...
95                        Apur Sansar    8.4          (1959)
96                        Kanchivaram    8.2          (2008)
97                    Monsoon Wedding    7.3          (2001)
98                              Black    8.1          (2005)
99                            Deewaar      8          (1975)

[100 rows x 3 columns]

 5)  Write a python program to scrape house details from mentioned URL. It should include house title, location,
     area, EMI and price

In [94]:
page=requests.get('https://www.nobroker.in/property/rent/chennai/Chennai/?searchParam=W3sibGF0IjoxMy4wNDM3NjEyODI5MTkyLCJsb24iOjgwLjIwMDA2ODUxNjk2OTMsInNob3dNYXAiOmZhbHNlLCJwbGFjZUlkIjoiQ2hJSllUTjlULXBsVWpvUk05UmphQXVuWVc0IiwicGxhY2VOYW1lIjoiQ2hlbm5haSIsImNpdHkiOiJjaGVubmFpIn1d&sharedAccomodation=0&orderBy=nbRank,desc&radius=2&traffic=true&travelTime=30&propertyType=rent&pageNo1')

In [95]:
page

In [96]:
soup=BeautifulSoup(page.content,'html')

In [97]:
Name=[]

for i in soup.find_all('h2',class_='heading-6 flex items-center font-semi-bold m-0'):
    Name.append(i.text.strip())

In [98]:
Location=[]

for i in soup.find_all('div',class_='mt-0.5p overflow-hidden overflow-ellipsis whitespace-nowrap max-w-70 text-gray-light leading-4 po:mb-0.1p po:max-w-95'):
    Location.append(i.text.strip())

In [99]:
EMI=[]

for i in soup.find_all('div',id='minimumRent'):
     EMI.append(i.text.strip())

In [101]:
Price=[]
for i in soup.find_all('div',id='roomType'):
    Price.append(i.text.strip())

In [102]:
len(Name),len(Location),len(EMI),len(Price)

(26, 26, 26, 26)

In [103]:
Home=pd.DataFrame({'Name':Name,'Location':Location,'Rent':EMI,'Deposite_price':Price})
Home

,Name,Location,Rent,Deposite_price
0,2 BHK Apartment In Urban Tree Oxygen for Rent ...,"Urban Tree Oxygen Nookampalayam Road, Off Gan...","₹ 19,000 +₹ 3,500Maintenance","₹80,000"
1,2 BHK House for Rent In Villivakkam Chennai,"Independent House, Nathamuni Theatre, TNHB Col...","₹ 13,700 +₹ 300Maintenance","₹75,000"
2,2 BHK House for Rent In Chromepet Chennai,"Independent House, Near GGN International School","₹ 15,500No Extra Maintenance","₹1,00,000"
3,3 BHK Flat for Rent In Thoraipakkam Chennai,"Standalone building, 200 Feet Radial Road, MCN...","₹ 28,000 +₹ 1,000Maintenance","₹1,50,000"
4,2 BHK Flat In Swaminathan Illam for Rent In P...,"Bharathi Nagar, Near QM Hospital","₹ 14,000 +₹ 1,000Maintenance","₹1,00,000"
5,2 BHK House for Rent In Saidapet Metro Chennai,"Independent House, 12/120 bazzar road saidapet...","₹ 18,000 +₹ 500Maintenance","₹1,00,000"
6,2 BHK Flat In Ponnamani Kudil for Rent In Sit...,"MAHESHWAR NAGAR MAIN ROAD, PRIYADHARSHNI NAGAR...","₹ 15,000 +₹ 1,000Maintenance","₹1,00,000"
7,2 BHK House for Rent In Velachery Chennai,"Independent House, Near Guru Nanak College, Gu...","₹ 15,000No Extra Maintenance","₹1,00,000"
8,1 BHK House for Rent In Iyappanthangal Chennai,"Independent House, Ramachandra Hospital, Sri R...","₹ 12,000No Extra Maintenance","₹50,000"
9,2 BHK Flat In Subhav Apartments for Rent In N...,"Kumarappa Steet, MANGADU SWAMY STREET,","₹ 24,400 +₹ 600Maintenance","₹2,10,000"
10,2 BHK House for Rent In Tiruvottiyur Chennai,"Independent House, sakthi puram 2nd street Ne...","₹ 11,000No Extra Maintenance","₹72,000"
11,2 BHK Flat In Eloi Flats for Lease In Palania...,St. Ann's Matriculation Higher Secondary Schoo...,"Only Deposit +₹ 1,000Maintenance","₹13,00,000"
12,2 BHK House for Rent In Kolathur Chennai,"Independent House, Perumal Nagar Near Indane -...","₹ 12,000 +₹ 700Maintenance","₹1,00,000"
13,2 BHK Flat In Zephyr Apartments for Rent In I...,saibaba koil street,"₹ 35,000No Extra Maintenance","₹2,50,000"
14,3 BHK Flat In Acchyuthans Sri Sudharsana for R...,5th Main Road,"₹ 25,000 +₹ 2,000Maintenance","₹1,50,000"
15,3 BHK Flat In Standalone Building for Rent I...,"near Elsan Public health Perumal Koil St, We...","₹ 25,000No Extra Maintenance","₹1,50,000"
16,2 BHK House for Rent In Valasaravakkam Chennai,"Independent House, Our Angel Matriculation Hig...","₹ 21,000No Extra Maintenance","₹2,00,000"
17,3 BHK House for Rent In Anna Nagar East Chennai,"Independent House, W Block, Near, PRR Travels...","₹ 30,000No Extra Maintenance","₹1,80,000"
18,"3 BHK Gated Community Villa In Doshi Gardens, ...","Arcot Road, Vadapalani, Chennai-600026, Tamil ...","₹ 35,000No Extra Maintenance","₹2,00,000"
19,2 BHK House for Rent In Pallavaram Chennai,"Independent House, Fathima manzil street","₹ 15,000No Extra Maintenance","₹1,00,000"
20,2 BHK Flat In Prithvi Apartment for Rent In V...,"98/104, Kaliamman Koil Street, Natesa Nagar, V...","₹ 17,600 +₹ 1,200Maintenance","₹1,00,000"
21,2 BHK House for Rent In Madipakkam Chennai,"Independent House, Moogambigai Temple, Kamala ...","₹ 19,000 +₹ 500Maintenance","₹1,20,000"
22,1 BHK House for Lease In Old Perungalathur Ch...,"Independent House, Indira Nagar Main Road, Nea...",Only DepositNo Extra Maintenance,"₹5,00,000"
23,2 BHK Apartment In Sriji Hill View Apartments ...,"Sriji Hill View Apartments Durga Nagar, Tamba...","₹ 12,000 +₹ 1,100Maintenance","₹60,000"
24,1 RK House for Rent In Maduravoyal Chennai,"Independent House, KKR ENT SUPER SPECIALTY HOS...","₹ 13,000No Extra Maintenance","₹50,000"
25,2 BHK Apartment In Urban Tree Oxygen for Rent ...,"Urban Tree Oxygen Nookampalayam Road, Off Gan...","₹ 19,000 +₹ 3,500Maintenance","₹80,000"

6) Write a python program to scrape first 10 product details which include product name , price , Image URL from
   https://www.bewakoof.com/bestseller?sort=popular .

In [2]:
page=requests.get('https://www.bewakoof.com/half-sleeve-t-shirts-for-women')
page

In [3]:
soup=BeautifulSoup(page.content,'html')

In [23]:
Product_name=[]
i=0

for name in soup.find_all('h2',class_='clr-shade4 h3-p-name   undefined false  '):
    if i>10:
        break
    Product_name.append(name.text.strip())
    i+=1

In [25]:
Price=[]
i=0

for price in soup.find_all('div',class_='discountedPriceText clr-p-black   false  '):
    if i>10:
        break
    Price.append(price.text)
    i+=1

In [26]:
Image=[]
i=0

for image in soup.find_all('img',class_='productImgTag'):
    if i>10:
        break
    Image.append(image['src'])
    i+=1

In [27]:
Image

['https://images.bewakoof.com/t640/women-s-black-100-responsible-graphic-printed-oversized-acid-wash-t-shirt-633706-1709198694-1.jpg',
 'https://images.bewakoof.com/t640/women-s-pink-100-responsible-graphic-printed-oversized-t-shirt-633708-1709118761-1.jpg',
 'https://images.bewakoof.com/t640/women-s-black-cat-o-clock-graphic-printed-oversized-t-shirt-630879-1707367806-1.jpg',
 'https://images.bewakoof.com/t640/women-s-black-illusion-graphic-printed-oversized-t-shirt-630875-1707367535-1.jpg',
 'https://images.bewakoof.com/t640/women-s-red-selective-participation-graphic-printed-plus-size-boyfriend-t-shirt-630772-1706686982-1.jpg',
 'https://images.bewakoof.com/t640/women-s-white-cool-pals-graphic-printed-plus-size-boyfriend-t-shirt-630776-1706687849-1.jpg',
 'https://images.bewakoof.com/t640/women-s-red-lovestruck-graphic-printed-oversized-t-shirt-630615-1706176717-1.jpg',
 'https://images.bewakoof.com/t640/women-s-black-sweet-memories-graphic-printed-boyfriend-t-shirt-629576-1705497772-1.jpg',
 'https://images.bewakoof.com/t640/women-s-navy-blue-dream-graphic-printed-oversized-t-shirt-629024-1703055098-1.jpg',
 'https://images.bewakoof.com/t640/women-s-black-boyfriend-t-shirt-103943-1655747735-1.jpg']

In [ ]:
Product=pd.DataFrame({'Product_name':Product_name,'Product_price':Price,'Image':Image})